"""Generate the class-filter build aliases from builderfilter/data/class-builds/<Class>.json.

Each class has its own JSON (refreshed from Hiim's tier lists on hiimpd2.com by
scripts/update-class-build-items.mjs, and safe to edit by hand) listing the uniques and set
items its builds wear. For every class this writes
02-alias/09-class-build-items[ONLY=<class tag>].filter with

    Alias[CLASS_BUILD_UNIQUE]: (<base codes of those uniques>)
    Alias[CLASS_BUILD_SET]:    (<base codes of those set items>)

which 04-Specialty/22-Class_Build_SafetyNet uses to keep the items visible at the stricter
filter levels in that class's filter. The alias files are generated on every build; edit
the JSON instead.

An entry needs a "name"; its base "code" is looked up by name in unique-set-tiers.json when
it is missing (give "code" for items that file doesn't list, e.g. unique rings / amulets).
"""
import json
import os

import tier_aliases

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(SCRIPT_DIR, "data", "class-builds")
ALIAS_DIR = os.path.join(SCRIPT_DIR, "02-alias")
# planner class name (JSON file name) -> class filter tag (builderfilter/filters.json)
CLASS_TAGS = {"Amazon": "Amazon", "Assassin": "Assassin", "Barbarian": "Barb", "Druid": "Druid",
              "Necromancer": "Necro", "Paladin": "Paladin", "Sorceress": "Sorc"}


class ClassBuildError(ValueError):
    pass


def alias_path(tag):
    return os.path.join(ALIAS_DIR, f"09-class-build-items[ONLY={tag}].filter")


def _norm(name):
    return "".join(ch for ch in name.lower() if ch.isalnum())


def _codes_by_name():
    tiers = tier_aliases.load()
    return {kind: {_norm(e["name"]): e["code"] for e in tiers[kind]} for kind in ("uniques", "sets")}


def _resolve(cls, kind, entries, lookup):
    out = []
    for e in entries:
        code = e.get("code") or lookup[kind].get(_norm(e["name"]))
        if not code:
            raise ClassBuildError(f"class-builds/{cls}.json: no base code for {kind[:-1]} "
                                  f"'{e['name']}' (add \"code\" or check the name)")
        out.append(dict(e, code=code))
    return out


def _block(alias, title, entries):
    out = [f"// {title}", "//-----------------------------------------------------------------------------------"]
    for e in entries:
        why = ", ".join(e.get("builds") or []) or ("added by hand" if e.get("manual") else "")
        out.append(f"// {e['name']} - {e.get('base') or e['code']}" + (f" ({why})" if why else ""))
    codes = sorted({e["code"] for e in entries})
    out.append(f"Alias[{alias}]: ({' OR '.join(codes)})" if codes else f"Alias[{alias}]: (FALSE)")
    out.append("")
    return out


def render(cls, data, lookup):
    exclude = set(data.get("exclude") or [])
    items = {kind: _resolve(cls, kind, [e for e in data.get(kind, []) if e["name"] not in exclude], lookup)
             for kind in ("uniques", "sets")}
    out = [
        "//-----------------------------------------------------------------------------------",
        f"// {cls} build items - GENERATED by builderfilter/class_build_aliases.py from",
        f"// builderfilter/data/class-builds/{cls}.json. Do not edit; change the JSON instead.",
        "//-----------------------------------------------------------------------------------",
        "",
    ]
    out += _block("CLASS_BUILD_UNIQUE", f"Uniques worn by {cls} builds", items["uniques"])
    out += _block("CLASS_BUILD_SET", f"Set items worn by {cls} builds", items["sets"])
    return "\r\n".join(out)


def generate():
    """Rewrite the per-class alias files. Returns the list of files that changed."""
    lookup = _codes_by_name()
    changed = []
    for cls, tag in CLASS_TAGS.items():
        path = os.path.join(DATA_DIR, f"{cls}.json")
        if os.path.exists(path):
            with open(path, encoding="utf-8") as f:
                data = json.load(f)
        else:  # no list yet: keep the aliases defined, matching nothing
            data = {"uniques": [], "sets": []}
        text = render(cls, data, lookup)
        target = alias_path(tag)
        old = None
        if os.path.exists(target):
            with open(target, encoding="utf-8", newline="") as f:
                old = f.read()
        if old != text:
            with open(target, "w", encoding="utf-8", newline="") as f:
                f.write(text)
            changed.append(target)
    return changed


if __name__ == "__main__":
    for p in generate():
        print("wrote " + os.path.relpath(p))
