type 00-Hiim_Top.filter 01-Version.filter 02-Hiim_Top.filter 02-Hiim_Top-End.filter 03-alias-general.filter 03-PD2_items.filter 04-Ubermats.filter 05-Maps.filter 06-Gems.filter 07-Runes.filter 07-Runes-ToolTip.filter 08-Potions.filter 09-QuestItems.filter 10-Formatted_MagRare_Names.filter 11-Formatted_MagRare_All.filter 12-Unid_MagRare.filter 13-Formatted_MagicRare.filter 14-RingAmuJewelPts.filter 15-Formatted_Charms.filter 16-Tags_All.filter 17-Tags_LLD.filter 18-Unid_UniquesSet_Name.filter 19-Tags_Unid_UniquesSet.filter 20-Unid_UniquesSet_Tiers.filter 21-Tags_Weap_range.filter 22-Tags_Shopping.filter 23-Tags_Crafting_Unid.filter 24-Tags_Crafting_Id.filter 25-Nmag_TopFilter.filter 26-Nmag_Staffmod.filter 27-Tags_Nmag_Sockets.filter 28-Tags_Nmag_runewords.filter 29-Tags_Nmag_bases.filter 30-Tags_Sockets_Upgrading.filter 31-Leveling.filter 32-Footer.filter 33-Gambleing.filter > "..\Hiim.filter"
type 00-Hiim_Top.filter 01-Version.filter 02-Hiim_Top-Hyper.filter 02-Hiim_Top-End.filter 03-alias-hyper.filter 03-PD2_items.filter 04-Ubermats.filter 05-Maps.filter 06-Gems.filter 07-Runes.filter 07-Runes-ToolTip.filter 08-Potions.filter 09-QuestItems.filter 10-Formatted_MagRare_Names.filter 11-Formatted_MagRare_All.filter 12-Unid_MagRare.filter 13-Formatted_MagicRare.filter 14-RingAmuJewelPts.filter 15-Formatted_Charms.filter 16-Tags_All.filter 17-Tags_LLD.filter 18-Unid_UniquesSet_Name.filter 19-Tags_Unid_UniquesSet.filter 20-Unid_UniquesSet_Tiers.filter 21-Tags_Weap_range.filter 22-Tags_Shopping.filter 23-Tags_Crafting_Unid.filter 24-Tags_Crafting_Id.filter 25-Nmag_TopFilter.filter 26-Nmag_Staffmod.filter 27-Tags_Nmag_Sockets.filter 28-Tags_Nmag_runewords.filter 29-Tags_Nmag_bases.filter 30-Tags_Sockets_Upgrading.filter 31-Leveling.filter 32-Footer.filter 33-Gambleing.filter > "..\Hiim_Hyper.filter"
type 00-Hiim_Top.filter 01-Version.filter 02-Hiim_Top-Crafting.filter 02-Hiim_Top-End.filter 03-alias-general.filter 03-PD2_items.filter 04-Ubermats.filter 05-Maps.filter 06-Gems-Crafting.filter 07-Runes-Crafting.filter 07-Runes-ToolTip.filter 08-Potions.filter 09-QuestItems.filter 10-Formatted_MagRare_Names.filter 11-Formatted_MagRare_All.filter 12-Unid_MagRare.filter 13-Formatted_MagicRare.filter 14-RingAmuJewelPts.filter 15-Formatted_Charms.filter 16-Tags_All.filter 17-Tags_LLD.filter 18-Unid_UniquesSet_Name.filter 19-Tags_Unid_UniquesSet.filter 20-Unid_UniquesSet_Tiers.filter 21-Tags_Weap_range.filter 22-Tags_Shopping.filter 23-Tags_Crafting_Unid-Crafting.filter 24-Tags_Crafting_Id.filter 25-Nmag_TopFilter.filter 26-Nmag_Staffmod.filter 27-Tags_Nmag_Sockets.filter 28-Tags_Nmag_runewords.filter 29-Tags_Nmag_bases.filter 30-Tags_Sockets_Upgrading.filter 31-Leveling.filter 32-Footer.filter 33-Gambleing.filter > "..\Hiim_Crafting.filter"
type 00-Hiim_Top.filter 01-Version.filter 02-Hiim_Top-Vanilla.filter 02-Hiim_Top-End.filter 03-alias-general.filter 03-PD2_items.filter 04-Ubermats.filter 05-Maps.filter 06-Gems.filter 07-Runes.filter 07-Runes-ToolTip.filter 08-Potions.filter 09-QuestItems.filter 11-Formatted_MagRare_All.filter 12-Unid_MagRare.filter 14-RingAmuJewelPts.filter 16-Tags_All.filter 17-Tags_LLD.filter 19-Tags_Unid_UniquesSet.filter 20-Unid_UniquesSet_Tiers.filter 21-Tags_Weap_range.filter 22-Tags_Shopping.filter 23-Tags_Crafting_Unid.filter 24-Tags_Crafting_Id.filter 25-Nmag_TopFilter.filter 26-Nmag_Staffmod.filter 27-Tags_Nmag_Sockets.filter 28-Tags_Nmag_runewords.filter 29-Tags_Nmag_bases.filter 30-Tags_Sockets_Upgrading.filter 31-Leveling.filter 32-Footer.filter 33-Gambleing.filter > "..\Hiim_Vanilla_Plus.filter"
type 00-Hiim_Top.filter 01-Version.filter 02-Hiim_Top-Mystery.filter 02-Hiim_Top-End.filter 03-alias-general.filter 03-PD2_items.filter 04-Ubermats-Mystery.filter 04-Ubermats.filter 05-Maps.filter 06-Gems.filter 07-Runes-Mystery.filter 07-Runes.filter 07-Runes-ToolTip.filter 08-Potions.filter 09-QuestItems.filter 10-Formatted_MagRare_Names.filter 11-Formatted_MagRare_All.filter 12-Unid_MagRare.filter 13-Formatted_MagicRare.filter 14-RingAmuJewelPts.filter 15-Formatted_Charms.filter 16-Tags_All.filter 17-Tags_LLD.filter 18-Unid_UniquesSet_Name.filter 19-Tags_Unid_UniquesSet.filter 20-Unid_UniquesSet_Tiers-Mystery.filter 20-Unid_UniquesSet_Tiers.filter 21-Tags_Weap_range.filter 22-Tags_Shopping.filter 23-Tags_Crafting_Unid.filter 24-Tags_Crafting_Id.filter 25-Nmag_TopFilter.filter 26-Nmag_Staffmod.filter 27-Tags_Nmag_Sockets.filter 28-Tags_Nmag_runewords.filter 29-Tags_Nmag_bases.filter 30-Tags_Sockets_Upgrading.filter 31-Leveling.filter 32-Footer.filter 33-Gambleing.filter > "..\Hiim_Mystery.filter"
type 00-Hiim_Top.filter 01-Version.filter 02-Hiim_Top-Crafting-Amazon.filter 02-Hiim_Top-End.filter 03-alias-general.filter 03-PD2_items.filter 04-Ubermats.filter 05-Maps.filter 06-Gems-Crafting.filter 07-Runes-Crafting.filter 07-Runes-ToolTip.filter 08-Potions.filter 09-QuestItems.filter 10-Formatted_MagRare_Names.filter 11-Formatted_MagRare_All.filter 23-Tags_Crafting_Unid_Amazon.filter 12-Unid_MagRare.filter 13-Formatted_MagicRare.filter 14-RingAmuJewelPts.filter 15-Formatted_Charms.filter 16-Tags_All.filter 17-Tags_LLD.filter 18-Unid_UniquesSet_Name.filter 19-Tags_Unid_UniquesSet.filter 20-Unid_UniquesSet_Tiers.filter 21-Tags_Weap_range.filter 22-Tags_Shopping.filter 24-Tags_Crafting_Id.filter 25-Nmag_TopFilter.filter 26-Nmag_Staffmod.filter 27-Tags_Nmag_Sockets.filter 28-Tags_Nmag_runewords.filter 29-Tags_Nmag_bases.filter 30-Tags_Sockets_Upgrading.filter 31-Leveling.filter 32-Footer.filter 33-Gambleing.filter > "..\Hiim_Crafting_Amazon_Focused.filter"
type 00-Hiim_Top.filter 01-Version.filter 02-Hiim_Top-Crafting-Assassin.filter 02-Hiim_Top-End.filter 03-alias-general.filter 03-PD2_items.filter 04-Ubermats.filter 05-Maps.filter 06-Gems-Crafting.filter 07-Runes-Crafting.filter 07-Runes-ToolTip.filter 08-Potions.filter 09-QuestItems.filter 10-Formatted_MagRare_Names.filter 11-Formatted_MagRare_All.filter 18-Unid_UniquesSet_Name.filter 19-Tags_Unid_UniquesSet.filter 23-Tags_Crafting_Unid_Assassin.filter 12-Unid_MagRare.filter 13-Formatted_MagicRare.filter 14-RingAmuJewelPts.filter 15-Formatted_Charms.filter 16-Tags_All.filter 17-Tags_LLD.filter 20-Unid_UniquesSet_Tiers.filter 21-Tags_Weap_range.filter 22-Tags_Shopping.filter 24-Tags_Crafting_Id.filter 25-Nmag_TopFilter.filter 26-Nmag_Staffmod.filter 27-Tags_Nmag_Sockets.filter 28-Tags_Nmag_runewords.filter 29-Tags_Nmag_bases.filter 30-Tags_Sockets_Upgrading.filter 31-Leveling.filter 32-Footer.filter 33-Gambleing.filter > "..\Hiim_Crafting_Assassin_Focused.filter"
type 00-Hiim_Top.filter 01-Version.filter 02-Hiim_Top-Crafting-Barbarian.filter 02-Hiim_Top-End.filter 03-alias-general.filter 03-PD2_items.filter 04-Ubermats.filter 05-Maps.filter 06-Gems-Crafting.filter 07-Runes-Crafting.filter 07-Runes-ToolTip.filter 08-Potions.filter 09-QuestItems.filter 10-Formatted_MagRare_Names.filter 11-Formatted_MagRare_All.filter 18-Unid_UniquesSet_Name.filter 19-Tags_Unid_UniquesSet.filter 23-Tags_Crafting_Unid_Barbarian.filter 12-Unid_MagRare.filter 13-Formatted_MagicRare.filter 14-RingAmuJewelPts.filter 15-Formatted_Charms.filter 16-Tags_All.filter 17-Tags_LLD.filter 20-Unid_UniquesSet_Tiers.filter 21-Tags_Weap_range.filter 22-Tags_Shopping.filter 24-Tags_Crafting_Id.filter 25-Nmag_TopFilter.filter 26-Nmag_Staffmod.filter 27-Tags_Nmag_Sockets.filter 28-Tags_Nmag_runewords.filter 29-Tags_Nmag_bases.filter 30-Tags_Sockets_Upgrading.filter 31-Leveling.filter 32-Footer.filter 33-Gambleing.filter > "..\Hiim_Crafting_Barbarian_Focused.filter"
type 00-Hiim_Top.filter 01-Version.filter 02-Hiim_Top-Crafting-Druid.filter 02-Hiim_Top-End.filter 03-alias-general.filter 03-PD2_items.filter 04-Ubermats.filter 05-Maps.filter 06-Gems-Crafting.filter 07-Runes-Crafting.filter 07-Runes-ToolTip.filter 08-Potions.filter 09-QuestItems.filter 10-Formatted_MagRare_Names.filter 11-Formatted_MagRare_All.filter 18-Unid_UniquesSet_Name.filter 19-Tags_Unid_UniquesSet.filter 23-Tags_Crafting_Unid_Druid.filter 12-Unid_MagRare.filter 13-Formatted_MagicRare.filter 14-RingAmuJewelPts.filter 15-Formatted_Charms.filter 16-Tags_All.filter 17-Tags_LLD.filter 20-Unid_UniquesSet_Tiers.filter 21-Tags_Weap_range.filter 22-Tags_Shopping.filter 24-Tags_Crafting_Id.filter 25-Nmag_TopFilter.filter 26-Nmag_Staffmod.filter 27-Tags_Nmag_Sockets.filter 28-Tags_Nmag_runewords.filter 29-Tags_Nmag_bases.filter 30-Tags_Sockets_Upgrading.filter 31-Leveling.filter 32-Footer.filter 33-Gambleing.filter > "..\Hiim_Crafting_Druid_Focused.filter"
type 00-Hiim_Top.filter 01-Version.filter 02-Hiim_Top-Crafting-Necromancer.filter 02-Hiim_Top-End.filter 03-alias-general.filter 03-PD2_items.filter 04-Ubermats.filter 05-Maps.filter 06-Gems-Crafting.filter 07-Runes-Crafting.filter 07-Runes-ToolTip.filter 08-Potions.filter 09-QuestItems.filter 10-Formatted_MagRare_Names.filter 11-Formatted_MagRare_All.filter 18-Unid_UniquesSet_Name.filter 19-Tags_Unid_UniquesSet.filter 23-Tags_Crafting_Unid_Necromancer.filter 12-Unid_MagRare.filter 13-Formatted_MagicRare.filter 14-RingAmuJewelPts.filter 15-Formatted_Charms.filter 16-Tags_All.filter 17-Tags_LLD.filter 20-Unid_UniquesSet_Tiers.filter 21-Tags_Weap_range.filter 22-Tags_Shopping.filter 24-Tags_Crafting_Id.filter 25-Nmag_TopFilter.filter 26-Nmag_Staffmod.filter 27-Tags_Nmag_Sockets.filter 28-Tags_Nmag_runewords.filter 29-Tags_Nmag_bases.filter 30-Tags_Sockets_Upgrading.filter 31-Leveling.filter 32-Footer.filter 33-Gambleing.filter > "..\Hiim_Crafting_Necromancer_Focused.filter"
type 00-Hiim_Top.filter 01-Version.filter 02-Hiim_Top-Crafting-Sorceress.filter 02-Hiim_Top-End.filter 03-alias-general.filter 03-PD2_items.filter 04-Ubermats.filter 05-Maps.filter 06-Gems-Crafting.filter 07-Runes-Crafting.filter 07-Runes-ToolTip.filter 08-Potions.filter 09-QuestItems.filter 10-Formatted_MagRare_Names.filter 11-Formatted_MagRare_All.filter 18-Unid_UniquesSet_Name.filter 19-Tags_Unid_UniquesSet.filter 23-Tags_Crafting_Unid_Sorceress.filter 12-Unid_MagRare.filter 13-Formatted_MagicRare.filter 14-RingAmuJewelPts.filter 15-Formatted_Charms.filter 16-Tags_All.filter 17-Tags_LLD.filter 20-Unid_UniquesSet_Tiers.filter 21-Tags_Weap_range.filter 22-Tags_Shopping.filter 24-Tags_Crafting_Id.filter 25-Nmag_TopFilter.filter 26-Nmag_Staffmod.filter 27-Tags_Nmag_Sockets.filter 28-Tags_Nmag_runewords.filter 29-Tags_Nmag_bases.filter 30-Tags_Sockets_Upgrading.filter 31-Leveling.filter 32-Footer.filter 33-Gambleing.filter > "..\Hiim_Crafting_Sorceress_Focused.filter"
type 00-Hiim_Top.filter 01-Version.filter 02-Hiim_Top-LLD.filter 02-Hiim_Top-End.filter 03-alias-general.filter 03-PD2_items.filter 04-Ubermats.filter 05-Maps.filter 06-Gems-Crafting.filter 07-Runes-Crafting.filter 07-Runes-ToolTip.filter 08-Potions.filter 09-QuestItems.filter 10-Formatted_MagRare_Names.filter 11-Formatted_MagRare_All.filter 18-Unid_UniquesSet_Name.filter 19-Tags_Unid_UniquesSet.filter 23-Tags_Crafting_Unid_LLD.filter 12-Unid_MagRare.filter 13-Formatted_MagicRare.filter 14-RingAmuJewelPts.filter 15-Formatted_Charms.filter 16-Tags_All.filter 17-Tags_LLD.filter 20-Unid_UniquesSet_Tiers.filter 21-Tags_Weap_range.filter 22-Tags_Shopping.filter 24-Tags_Crafting_Id.filter 25-Nmag_TopFilter.filter 26-Nmag_Staffmod.filter 27-Tags_Nmag_Sockets.filter 28-Tags_Nmag_runewords.filter 29-Tags_Nmag_bases.filter 30-Tags_Sockets_Upgrading.filter 31-Leveling.filter 32-Footer.filter 33-Gambleing.filter > "..\Hiim_LLD_Focused.filter"
type 00-Hiim_Top.filter 01-Version.filter 02-Hiim_Top-Only-Filter.filter 02-Hiim_Top-End.filter 03-alias-onlyfilter.filter 03-PD2_items.filter 04-Ubermats.filter 06-Gems.filter 08-Potions.filter 09-QuestItems.filter 19-Tags_Unid_UniquesSet.filter 23-Tags_Crafting_Unid.filter 12-Unid_MagRare.filter 20-Unid_UniquesSet_Tiers.filter 29-Tags_Nmag_bases.filter 31-Leveling.filter 32-Footer.filter > "..\Hiim_Only_Filter.filter"
@echo off
setlocal enabledelayedexpansion

:: === Configuration ===
set "sourceFile=README.md"
set "keyword={{REPLACE_ME}}"
set "replacementFile=01-Version.filter"
set "finalFile=..\README.md"

:: === Read the replacement text into a variable ===
set "replacementText="
for /f "usebackq delims=" %%A in ("%replacementFile%") do (
    set "line=%%A"
    set "line=!line:%%CL%%= !"
    set "replacementText=!replacementText!!line!\n"
)

:: Remove trailing newline
set "replacementText=!replacementText:~0,-2!"

:: === Replace keyword with replacement text ===
> "%finalFile%" (
    for /f "usebackq delims=" %%A in ("%sourceFile%") do (
        set "line=%%A"
        set "line=!line:%keyword%=%replacementText%!"
        echo(!line!
    )
)
echo Done. "%keyword%" replaced in "%sourceFile%".